Keryan
La-Caverne-aux-Lapins-Noirs/Infosphere pull request #1
Opened 2024-08-20 11:47 UTC by Firekiking84

2024-08-20 11:59 UTC, Damdoshi requested changes

2024-08-20 11:59 UTC, Damdoshi commented on index.phtml
> +<<html>
What?

2024-08-20 11:59 UTC, Damdoshi commented on tools/hand_request.php
> +//    AddDebugLogR(openssl_encrypt("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFH7deW0nEXUguEAmeeX7WCfRzv5nM5LQHeGPC+cy7qz kgalaxie84@gmail.com", "blowfish", $acc.$url."hand_request", 0, "azertyui"));
A retirer

2024-08-20 11:59 UTC, Damdoshi commented on tools/profile_stats.php
> +$dbg = true;
A retirer

2024-08-20 11:59 UTC, Damdoshi commented on tools/profile_stats.php
> +error_clear_last();
A retirer, sinon le gest_last risque pas de se produire

2024-08-20 11:59 UTC, Damdoshi commented on tools/utc0_to_local.php
> +    function utc0_to_local($direction, $dt)
What again?
Qu'est ce qu'il se passe la?

2024-08-20 12:02 UTC, Firekiking84 commented on index.phtml
> +<<html>
Missclick

2024-08-21 13:22 UTC, Damdoshi approved these changes

2024-08-21 13:23 UTC, merged